trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: scope
  value: /providers/Microsoft.Management/managementGroups/mg-prd
- name: azureResourceManagerConnection
  value: sc-augp

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Deploy Tagging Standard
    inputs:
      deploymentScope: 'Management Group'
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      location: 'West Europe'
      templateLocation: 'Linked artifact'
      csmFile: 'tags/template.json'
      csmParametersFile: 'tags/parameters.json'
      deploymentMode: 'Incremental'
      overrideParameters: -scope "$(scope)"
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Deploy Tagging Standard
    inputs:
      deploymentScope: 'Management Group'
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      location: 'West Europe'
      templateLocation: 'Linked artifact'
      csmFile: 'tags/roleTemplate.json'
      csmParametersFile: 'tags/roleTemplate.parameters.json'
      deploymentMode: 'Incremental'
      overrideParameters: -scope "$(scope)"
  - task: PowerShell@2
    displayName: Conveert template before deployment
    inputs:
      targetType: 'inline'
      script: |
        $template = Get-Content -Path ./advanced/template.json
        $template -join '' | Out-File -FilePath ./advanced/template.json

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Deploy naming standard
    inputs:
      deploymentScope: 'Management Group'
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      location: 'West Europe'
      templateLocation: 'Linked artifact'
      csmFile: 'advanced/template.json'
      csmParametersFile: 'advanced/parameters.json'
      deploymentMode: 'Incremental'
      overrideParameters: -scope "$(scope)"