trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Management Group'
      azureResourceManagerConnection: 'sc-mg-dev'
      location: 'West Europe'
      templateLocation: 'Linked artifact'
      csmFile: 'simple/template.json'
      csmParametersFile: 'simple/parameters.json'
      deploymentMode: 'Incremental'
      overrideParameters: -scope "/providers/Microsoft.Management/managementGroups/mg-devsecops-dev"